# Generated by Django 2.2.28 on 2025-07-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('mac_toggle', models.CharField(max_length=17)),
                ('isEvenOrOdd', models.CharField(max_length=4)),
                ('dhcp_version', models.CharField(choices=[('DHCPv4', 'DHCPv4'), ('DHCPv6', 'DHCPv6')], max_length=6)),
                ('assigned_ip', models.CharField(max_length=45)),
                ('lease_time', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
